title: Code thinking
description: Explorant idees i compartint coneixement
baseurl: ""
url: "https://raquelalaman.github.io"

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
